PROJECT: SIMUTOOL
DOMAIN_NAME: http://example.org/abox
BLACKLIST:
    - create
    - merge
    - delete
    - set
    - remove
TERMS:
    - subclass_of: subclass_of
    - instance_of: type
    - identifier: identifier
    - model: ABox
    - meta: TBox